# These are supported funding model platforms

custom: ["https://www.paypal.com/donate/?business=5ZA6ULEBTHTA4&no_recurring=0&item_name=Help+keep+me+fueled+for+the+development%2C+and+management%2C+of+Heat.js%21&currency_code=GBP"]
